# name of the software
name: ID-porten SAML dokumentasjon
siteUrlText: http://difi.github.io/begrep-ID-porten/

# current version of the software
version: Staging

# licence of the software
license: GPL-3 License
licenseUrl: http://opensource.org/licenses/GPL-3.0

#baseurl: "/meldingsutveksling-mellom-offentlige-virksomheter" # the subpath of your site, e.g. /blog/
baseurl: "/begrep-ID-porten"

##Version handling
currentCollecion: "vStaging"
currentVersion: "Staging"
versions: ["Staging"]

# Collection of versions
collections:
  vStaging:  
    output: true
    permalink: /vStaging/

aboutSide: "about.html"
## End of Version handling

# list of additional links on the right of the top menu
headerLinks:
  - title: Om ID-porten SAML
    url: /begrep-ID-porten/about.html

# github buttons
githubButton:
  user: difi
  repo: begrep-ID-porten

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  account:
  domain:

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

kramdown:
  input: GFM
